set clipboard=unnamedplus
set cmdheight=1
set conceallevel=2
set fileencoding=utf-8
set noignorecase
set mouse=a
set pumheight=10
set showtabline=2
set smartcase
set smartindent
set noswapfile
set termguicolors
set undofile
set updatetime=300
set expandtab
set shiftwidth=4
set tabstop=4
set cursorline
set number
set relativenumber
set numberwidth=4
set signcolumn=yes
set wrap
set scrolloff=2
set sidescrolloff=2
